name: JMeter Load Test

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
          tar -xvzf apache-jmeter-5.4.1.tgz
          sudo mv apache-jmeter-5.4.1 /opt/jmeter

      - name: Run JMeter Test
        run: |
          /opt/jmeter/bin/jmeter -n -t your_test_plan.jmx -l result.jtl
        continue-on-error: true

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.jtl

     - name: JMeter Test
     uses: QAInsights/PerfAction@v5.6.2
     with:
     test-plan-path: ./TestPlans/S01_SimpleExample/S01_SimpleExample.jmx
     args: ""
     - name: Upload Results
     uses: actions/upload-artifact@v3
      with:
     name: jmeter-results
     path: result.jtl
     if-no-files-found: error 
          
